# Chỉ cần bỏ file này vào .github/workflows của bất kỳ repo nào sẽ tự chạy
# Workflow mẫu basic nhất.
name: CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Option này giúp hiện nút run workflow để bấm chạy thủ công được ở action tabs 

jobs: # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  build:
    runs-on: ubuntu-latest # Job chạy trên loại runner nào
    steps:
      - uses: actions/checkout@v3 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Run a one-line script # Chạy 1 single command trên shell
        run: echo Hello, world!
      - name: Run a multi-line script # Chạy nhiều lệnh tuần tự trên shell với |
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  test:
    runs-on: ubuntu-latest
    needs: [build] # Mặc định chạy song song, bh test chỉ chạy sau build
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        run: echo Test is running!!